services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - appnet

  web:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 3

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:alpine
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
